name: Build PhotoSaver for Godot 4.6.3

on:
  workflow_dispatch:

jobs:
  build-photosaver:

    name: PhotoSaver - Godot 4.6.3

    runs-on: macos-15-intel

    steps:

      - name: Checkout Fluxus PhotoSaver repository
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'

